# Tips on Numpy
+ 01.引入Numpy包
- 02.ndarray类型对象主要属性
- 03.创建ndarray
- 04.ndarray的数据类型
- 05.索引和切片
- 06.Numpy数组的迭代
- 07.Numpy数组操作
- 08.元素级数组函数
- 09.Numpy字符串函数
- 10.Numpy统计函数
- 11.排序、搜索和计数
- 12.线性代数
- 13.Numpy IO

## 01.引入Numpy包

In [15]:
#产生一个2*3的随机矩阵
import numpy as np
data = np.random.randn(2, 3) #numpy包random模块内的randn
print('data:',data)
print('shape:',data.shape)

data: [[ 1.00582499  0.0502911   0.55043631]
 [ 1.05483329  0.03742705 -0.86588302]]
shape: (2, 3)


In [14]:
#或这样引入,即把numpy整个引入
from numpy import *
lst = [0, 1, 2, 3]
a = array(lst) #传入一个list
print('a:',a)
print('ndim:',a.ndim)

a: [0 1 2 3]
ndim: 1


###   array函数可以接受如下参数：
&emsp;np.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0)
+ dtype：数组的所需数据类型，可选。
+ copy：可选，默认为true，对象是否被复制。
+ order：C(按行)、F(按列)或A(任意，默认)。
+ subok：默认情况下，返回的数组被强制为基类数组。 如果为true，则返回子类。
+ ndimin：指定返回数组的最小维数，亦即数组轴的个数，在python的世界中，轴的个数被称作秩。

In [8]:
import numpy as np 
a = np.array([1,  2,  3,4,5], ndmin =  2)  
print('a:',a)

a: [[1 2 3 4 5]]


In [9]:
import numpy as np 
a = np.array([1,  2,  3], dtype = complex) #从这可以看出，ndarray的所有元素必须是同类型的
print('a:',a)

a: [ 1.+0.j  2.+0.j  3.+0.j]


## 02.ndarray类型对象主要属性：
+ ndarray.ndim：
数组轴的个数，在python的世界中，轴的个数被称作秩
+ ndarray.shape：
数组的维度。这是一个指示数组在每个维度上大小的整数元组。例如一个n排m列的矩阵，它的shape属性将是(2,3),这个元组的长度显然是秩，即维度或者ndim属性
+ ndarray.size：数组元素的总个数，等于shape属性中元组元素的乘积。
+ ndarray.dtype:一个用来描述数组中元素类型的对象，可以通过创造或指定dtype使用标准Python类型。另外NumPy提供它自己的数据类型。
+ ndarray.itemsize：数组中每个元素的字节大小。例如，一个元素类型为float64的数组itemsiz属性值为8(=64/8),又如，一个元素类型为complex32的数组item属性为4(=32/8).
+ ndarray.nbytes：查看所有元素所占的空间，但事实上，数组所占的存储空间要比这个数字大，因为要用一个header来保存shape，dtype这样的信息。

In [27]:
import numpy as np 
a = np.array([1,  2,  3,4,5], ndmin =  2)  
print('a:',a)
a.dtype

a: [[1 2 3 4 5]]


dtype('int32')

## 03.创建ndarray

In [18]:
#其一是array函数
import numpy as np
data = np.array([[1,2,3,4],[5,6,7,8]])
print('data:\n',data)

data:
 [[1 2 3 4]
 [5 6 7 8]]


In [23]:
#还有许多创造特殊矩阵的方法，如上面的 np.random.randn(n,m)
#此外还有arange，这是Python内置函数range的数组版
import numpy as np
print(np.arange(15))
np.arange(15).reshape(3,5) #调用reshape方法是创建了一个新的数据对象，不是ndarray的视图

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

&emsp;numpy.linspace(start, stop, num, endpoint, retstep, dtype)：此函数类似于arange()函数。 在此函数中，指定了范围之间的均匀间隔数量，而不是步长。Tips:
1.	start 序列的起始值
2.	stop 序列的终止值，如果endpoint为true，该值包含于序列中
3.	num 要生成的等间隔样例数量，默认为50
4.	endpoint 序列中是否包含stop值，默认为ture
5.	retstep 如果为true，返回样例，以及连续数字之间的步长
6.	dtype 输出ndarray的数据类型

In [57]:
import numpy as np
x = np.linspace(10,20,5)  
x

array([ 10. ,  12.5,  15. ,  17.5,  20. ])

&emsp;此外，还有许多创建 **特殊矩阵** 的方法，如：

In [31]:
a = np.zeros((2,2)) #全零矩阵
a

array([[ 0.,  0.],
       [ 0.,  0.]])

In [26]:
b = np.ones((4,2)) #全一矩阵
b

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [28]:
c = np.full((2,2), 7) #全常数矩阵
c

array([[7, 7],
       [7, 7]])

In [29]:
d = np.eye(2) #或者用identity，单位矩阵
d

array([[ 1.,  0.],
       [ 0.,  1.]])

In [41]:
e = np.empty((3,4)) #只创建新数组，分配内存空间，但不填充任何值
e

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

### 04.ndarray的数据类型

&emsp;dtype是数据类型对象，描述了对应于数组的固定内存块的解释，反映的是ndaaray的数据类型。
语法构成：
    numpy.dtype(object, align, copy)
+ object：被转换为数据类型的对象。
+ align：如果为true，则向字段添加间隔，使其类似 C 的结构体。
+ copy：是否成dtype对象的新副本，如果为flase，结果是内建数据类型对象的引用。

In [47]:
# 使用数组标量类型  
import numpy as np 
dt = np.dtype(np.int32)  #int32可以用类型代码'i4'，具体各种类型代码见文档
dt

dtype('int32')

In [46]:
# 使用端记号  
import numpy as np 
dt = np.dtype('>i4')  
dt

dtype('>i4')

In [49]:
#本例子展示了结构化数据类型的使用，这里声明了字段名称和相应的标量数据类型
# 首先创建结构化数据类型。  
import numpy as np 
dt = np.dtype([('age',np.int8)])  
print(dt)

[('age', 'i1')]


In [53]:
# 现在将其应用于 ndarray 对象  
import numpy as np 
dt = np.dtype([('age',np.int8)]) 
a = np.array([(10,),(20,),(30,)], dtype = dt)
print(a)
a.dtype

[(10,) (20,) (30,)]


dtype([('age', 'i1')])

每个内建类型都有一个唯一定义它的字符代码：

- 'b'：布尔值

- 'i'：符号整数

- 'u'：无符号整数

- 'f'：浮点

- 'c'：复数浮点

- 'm'：时间间隔

- 'M'：日期时间

- 'O'：Python 对象

- 'S', 'a'：字节串

- 'U'：Unicode

- 'V'：原始数据(void)

&emsp;你可以通过ndarray的 ***astype*** 方法明确地将一个数组从一个dtype转换成另一个dtype：

In [56]:
arr = np.array([1, 2, 3, 4, 5])
print('arr:',arr.dtype)
float_arr = arr.astype(np.float64)
print('float_arr:',float_arr.dtype)

arr: int32
float_arr: float64


&emsp;调用astype总会创建一个新的数组（一个数据的备份），即使新的dtype与旧的dtype相同。(在本例中，整数被转换成了浮点数。如果将浮点数转换成整数，则小数部分将会被截取删除)

## 05.索引和切片

### 基本切片和索引

In [60]:
import numpy as np
arr = np.arange(10)
print('arr[5]:',arr[5])

arr[5]: 5


In [61]:
arr[5:8]

array([5, 6, 7])

In [62]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

&emsp;如上所示，当你将一个标量值赋值给一个切片时（如arr[5:8]=12），该值会自动传播（也就说后面将会讲到的“广播”）到整个选区。跟列表最重要的区别在于，数组切片是原始数组的视图。这意味着数据不会被复制，视图上的任何修改都会直接反映到源数组上。例子：

In [63]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

&emsp;现在，当修改arr_slice中的值，变动也会体现在原始数组arr中：

In [66]:
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,     9])

&emsp;如果你想要得到的是ndarray切片的一份副本而非视图，就需要明确地进行复制操作，例如arr[5:8].copy()。

&emsp;切片[ : ]会给数组中的所有值赋值：

In [68]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [69]:
#对于高维ndarray，也有类似操作
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

In [70]:
arr2d[0][2]

3

In [71]:
arr2d[0, 2]

3

!['二维数组轴0和轴1'](https://upload-images.jianshu.io/upload_images/7178691-0a641536f73f560e.png?imageMogr2/auto-orient/)

In [23]:
#一维切片索引
import numpy as np
arr = np.arange(10)
arr[1:6]

array([1, 2, 3, 4, 5])

In [74]:
#高维的切片索引略有不同
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [75]:
arr2d[:2] #可以看出，它是沿着第0轴（即第一个轴）切片的

array([[1, 2, 3],
       [4, 5, 6]])

In [78]:
arr2d[:2, 1:] #选取第1到2行，第2到3列

array([[2, 3],
       [5, 6]])

In [79]:
arr2d[:, :1] #选取第1列

array([[1],
       [4],
       [7]])

### 整数索引

In [80]:
import numpy as np 
x = np.array([[1,  2],  [3,  4],  [5,  6]]) 
y = x[[0,1,2],  [0,1,0]]  #该结果包括数组中(0,0)，(1,1)和(2,0)位置处的元素
print(y)

[1 4 5]


### 布尔索引

In [12]:
import numpy as np
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)

In [11]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'],
      dtype='<U4')

In [13]:
data

array([[-0.14072264, -0.05718019,  1.06168101, -0.99560633],
       [-0.84469087,  0.86920795,  1.21847825,  1.08733957],
       [-0.6423343 , -1.27024143, -0.23759937, -0.00214576],
       [-0.07324052, -0.7320548 ,  0.28645377, -0.49701037],
       [ 0.09944885,  0.54162591,  1.05353269, -1.01241262],
       [-1.07249176, -0.22839131,  0.59959029,  0.32680663],
       [ 0.07905383,  0.8507808 ,  1.45121678, -0.68472035]])

In [14]:
names == 'Bob'

array([ True, False, False,  True, False, False, False], dtype=bool)

In [15]:
data[names == 'Bob'] #可以用names=='Bob'进行数组索引，等效于取0行和3行

array([[-0.14072264, -0.05718019,  1.06168101, -0.99560633],
       [-0.07324052, -0.7320548 ,  0.28645377, -0.49701037]])

In [16]:
data[names == 'Bob', 2:] #选取第0，3行，第3及之后的列

array([[ 1.06168101, -0.99560633],
       [ 0.28645377, -0.49701037]])

In [17]:
data[names == 'Bob', 3] #选取第0，3行，第4列

array([-0.99560633, -0.49701037])

&emsp;在Numpy中使用与或非，要使用**& | ~**

### 花式索引

In [25]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [26]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]] #选取左边的行，并按右边的顺序将列排序

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

## 06.Numpy数组的迭代

&emsp;迭代器对象numpy.nditer

In [29]:
import numpy as np
a = np.arange(1,17,3)
a

array([ 1,  4,  7, 10, 13, 16])

In [32]:
for x in np.nditer(a):
    print(x)

1
4
7
10
13
16


&emsp;nditer对象有另一个可选参数op_flags。 其默认值为只读，但可以设置为读写或只写模式。 这将允许使用此迭代器修改数组元素。

In [46]:
import numpy as np
a = np.arange(0,60,5) 
a = a.reshape(3,4) 
a

array([[ 0,  5, 10, 15],
       [20, 25, 30, 35],
       [40, 45, 50, 55]])

In [48]:
for x in np.nditer(a, op_flags=['readwrite']):
    x[...]=2*x
a

array([[  0,  10,  20,  30],
       [ 40,  50,  60,  70],
       [ 80,  90, 100, 110]])

&emsp;**广播迭代：**如果两个数组是可广播的，nditer组合对象能够同时迭代它们。 假设数组a具有维度 3X4，并且存在维度为 1X4 的另一个数组b，则使用以下类型的迭代器(数组b被广播到a的大小)。

In [50]:
import numpy as np 
a = np.arange(0,60,5) 
a = a.reshape(3,4) 
a

array([[ 0,  5, 10, 15],
       [20, 25, 30, 35],
       [40, 45, 50, 55]])

In [51]:
b = np.array([1,  2,  3,  4], dtype =  int)
b

array([1, 2, 3, 4])

In [62]:
for x,y in np.nditer([a,b]):
    print(x,':',y)

0 : 1
5 : 2
10 : 3
15 : 4
20 : 1
25 : 2
30 : 3
35 : 4
40 : 1
45 : 2
50 : 3
55 : 4


## 07.Numpy数组操作

&emsp;&emsp;**修改形状**
1.	reshape 不改变数据的条件下修改形状
2.	flat 数组上的一维迭代器
3.	flatten 返回折叠为一维的数组副本
4.	ravel 返回连续的展开数组
+ transpose 转置  
**修改维度**
5.  broadcast 产生模仿广播的对象
6.  broadcast_to 将数组广播到新形状
7.  expand_dims 扩展数组的形状
8.  squeeze 从数组的形状中删除单维条目  
**数组连接**
9.  concatenate 沿着现存的轴连接数据序列
10. stack 沿着新轴连接数组序列
11. hstack 水平堆叠序列中的数组(列方向)
12. vstack 竖直堆叠序列中的数组(行方向)  
**数组分割**
13. split 将一个数组分割为多个子数组
14. hsplit 将一个数组水平分割为多个子数组(按列)
15. vsplit 将一个数组竖直分割为多个子数组(按行)  
**增删元素**
16. resize 返回指定形状的新数组
17. append 将值添加到数组末尾
18. insert 沿指定轴将值插入到指定下标之前
19. delete 返回删掉某个轴的子数组的新数组
20. unique 寻找数组内的唯一元素

### numpy.ndarray.flat
&emsp;该函数返回数组上的一维迭代器，行为类似 Python 内建的迭代器。

In [67]:
import numpy as np
a = np.arange(8).reshape(2,4)
print(a)

# 返回展开数组中的下标的对应元素
print('下标5的数:',a.flat[5])

[[0 1 2 3]
 [4 5 6 7]]
下标5的数: 5


## numpy.ndarray.flatten
该函数返回折叠为一维的数组副本，函数接受下列参数：ndarray.flatten(order)
+ order：'C' — 按行，'F' — 按列，'A' — 原顺序，'k' — 元素在内存中的出现顺序

In [70]:
import numpy as np
a = np.arange(8).reshape(2,4)
a # default is column-major

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [71]:
a.flatten() #展开的数组

array([0, 1, 2, 3, 4, 5, 6, 7])

In [72]:
a.flatten(order = 'F') #按F风格展开，即按列

array([0, 4, 1, 5, 2, 6, 3, 7])

### numpy.ravel
这个函数返回展开的一维数组，并且按需生成副本。返回的数组和输入数组拥有相同数据类型。这个函数接受两个参数。numpy.ravel(a, order)

In [2]:
import numpy as np
a = np.arange(8).reshape(2,4)
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [3]:
a.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7])

In [4]:
a.ravel(order = 'F')

array([0, 4, 1, 5, 2, 6, 3, 7])

### np.broadcast
&emsp;如前所述，NumPy 已经内置了对广播的支持。 此功能模仿广播机制。 它返回一个对象，该对象封装了将一个数组广播到另一个数组的结果。该函数使用两个数组作为输入参数。

In [15]:
import numpy as np
x = np.array([[1], [2], [3]])
y = np.array([4, 5, 6])  

# 对 y 广播 x
b = np.broadcast(x,y)  
# 它拥有 iterator 属性，基于自身组件的迭代器元组
(r,c)=b.iters
for a in r:
    print(a)

1
1
1
2
2
2
3
3
3


In [10]:
for d in c:
    print(d)

4
5
6
4
5
6
4
5
6


In [16]:
b.shape

(3, 3)

### np.expand_dims
函数通过在指定位置插入新的轴来扩展数组形状。该函数需要两个参数：numpy.expand_dims(arr, axis)

In [19]:
import numpy as np
x = np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [21]:
y = np.expand_dims(x, axis = 0)
y

array([[[1, 2],
        [3, 4]]])

In [22]:
z = np.expand_dims(x, axis = 1)
z

array([[[1, 2]],

       [[3, 4]]])

In [23]:
x.shape

(2, 2)

In [24]:
y.shape

(1, 2, 2)

In [25]:
z.shape

(2, 1, 2)

### np.squeeze
&emsp;函数从给定数组的形状中删除一维条目。 此函数需要两个参数。numpy.squeeze(arr, axis)


In [26]:
import numpy as np  
x = np.arange(9).reshape(1,3,3)
x

array([[[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]])

In [27]:
y = np.squeeze(x)
y

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [28]:
x.shape, y.shape

((1, 3, 3), (3, 3))

### np.concatenate
数组的连接是指连接。 此函数用于沿指定轴连接相同形状的两个或多个数组。 该函数接受以下参数。
numpy.concatenate((a1, a2, ...), axis)


In [29]:
import numpy as np
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [30]:
b = np.array([[5,6],[7,8]])
b

array([[5, 6],
       [7, 8]])

In [31]:
np.concatenate((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [32]:
np.concatenate((a,b),axis = 1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

### numpy.stack
此函数沿新轴连接数组序列。 此功能添加自 NumPy 版本 1.10.0。 需要提供以下参数。numpy.stack(arrays, axis)

In [33]:
import numpy as np
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [35]:
b = np.array([[5,6],[7,8]])
b

array([[5, 6],
       [7, 8]])

In [42]:
print(np.stack((a,b),0))
np.stack((a,b),0).shape

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


(2, 2, 2)

In [43]:
print(np.stack((a,b),1))
np.stack((a,b),1).shape

[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


(2, 2, 2)

### numpy.hstack
numpy.stack函数的变体，通过堆叠来生成水平的单个数组。

In [44]:
c = np.hstack((a,b))
c

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

### numpy.vstack
numpy.stack函数的变体，通过堆叠来生成竖直的单个数组。

In [45]:
d = np.vstack((a,b))
d

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

## 数组分割
### numpy.split
该函数沿特定的轴将数组分割为子数组。函数接受三个参数：numpy.split(ary, indices_or_sections, axis)
+ indices_or_sections：可以是整数，表明要从输入数组创建的，等大小的子数组的数量。 如果此参数是一维数组，则其元素表明要创建新子数组的点。


In [47]:
import numpy as np
a = np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [48]:
b = np.split(a,3)
b

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [49]:
c = np.split(a,[4,7])
c

[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8])]

### numpy.hsplit
numpy.hsplit是split()函数的特例，其中轴为 1 表示水平分割，无论输入数组的维度是什么。

In [50]:
import numpy as np
a = np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [52]:
b = np.hsplit(a,2)
b

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

### numpy.vsplit
numpy.vsplit是split()函数的特例，其中轴为 0 表示竖直分割，无论输入数组的维度是什么。下面的例子使之更清楚。

In [53]:
c = np.vsplit(a,2)
c

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

## 增删元素
### numpy.resize
此函数返回指定大小的新数组。 如果新大小大于原始大小，则包含原始数组中的元素的重复副本。 该函数接受以下参数。numpy.resize(arr, shape)

In [58]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
a,a.shape

(array([[1, 2, 3],
        [4, 5, 6]]), (2, 3))

In [57]:
b = np.resize(a, (3,2))
b,b.shape

(array([[1, 2],
        [3, 4],
        [5, 6]]), (3, 2))

In [60]:
c = np.resize(a,(3,3))
c

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

### numpy.append
此函数在输入数组的末尾添加值。 附加操作不是原地的，而是分配新的数组。 此外，输入数组的维度必须匹配否则将生成ValueError。numpy.append(arr, values, axis)
+ values：要向arr添加的值，比如和arr形状相同(除了要添加的轴)


In [61]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [63]:
np.append(a, [7,8,9]) #创建了副本，不对原数组产生影响

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
np.append(a, [[7,8,9]],axis = 0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [65]:
np.append(a, [[5,5,5],[7,8,9]],axis = 1)

array([[1, 2, 3, 5, 5, 5],
       [4, 5, 6, 7, 8, 9]])

### numpy.insert
此函数在给定索引之前，沿给定轴在输入数组中插入值。 如果值的类型转换为要插入，则它与输入数组不同。 插入没有原地的，函数会返回一个新数组。 此外，如果未提供轴，则输入数组会被展开。numpy.insert(arr, obj, values, axis)
- obj：在其之前插入值的索引
- values：要插入的值
- axis：沿着它插入的轴，如果未提供，则输入数组会被展开

In [66]:
import numpy as np
a = np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [67]:
np.insert(a,3,[11,12]) #在索引为3的元素之前插入11和12， 在插入之前输入数组会被展开

array([ 1,  2,  3, 11, 12,  4,  5,  6])

In [68]:
np.insert(a,1,[11],axis = 0)

array([[ 1,  2],
       [11, 11],
       [ 3,  4],
       [ 5,  6]])

In [70]:
np.insert(a,1,11,axis = 1)

array([[ 1, 11,  2],
       [ 3, 11,  4],
       [ 5, 11,  6]])

### numpy.delete
此函数返回从输入数组中删除指定子数组的新数组。 与insert()函数的情况一样，如果未提供轴参数，则输入数组将展开。 该函数接受以下参数：Numpy.delete(arr, obj, axis)
- obj：可以是切片，整数或者整数数组，表明要从输入数组删除的子数组
- axis：沿着它删除给定子数组的轴，如果未提供，则输入数组会被展开

In [71]:
import numpy as np
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [72]:
np.delete(a,5)

array([ 0,  1,  2,  3,  4,  6,  7,  8,  9, 10, 11])

In [73]:
np.delete(a,1,axis = 1)

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11]])

In [74]:
np.delete(a,1,axis = 0)

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [76]:
b = np.array([1,2,3,4,5,6,7,8,9,10])
np.delete(b, np.s_[::2])

array([ 2,  4,  6,  8, 10])

### numpy.unique
此函数返回输入数组中的去重元素数组。 该函数能够返回一个元组，包含去重数组和相关索引的数组。 索引的性质取决于函数调用中返回参数的类型.  
numpy.unique(arr, return_index, return_inverse, return_counts)
- return_index：如果为true，返回输入数组中的元素下标
- return_inverse：如果为true，返回去重数组的下标，它可以用于重构输入数组
- return_counts：如果为true，返回去重数组中的元素在原数组中的出现次数
![](https://upload-images.jianshu.io/upload_images/7178691-80e85ae6b9c89ada.png?imageMogr2/auto-orient/)

In [77]:
import numpy as np
a = np.array([5,2,6,2,7,5,6,8,2,9])
a

array([5, 2, 6, 2, 7, 5, 6, 8, 2, 9])

In [78]:
np.unique(a)

array([2, 5, 6, 7, 8, 9])

In [79]:
np.unique(a, return_index = True)

(array([2, 5, 6, 7, 8, 9]), array([1, 0, 2, 4, 7, 9], dtype=int64))

In [80]:
np.unique(a,return_inverse = True)

(array([2, 5, 6, 7, 8, 9]), array([1, 0, 2, 0, 3, 1, 2, 4, 0, 5], dtype=int64))

In [81]:
np.unique(a,return_counts = True)

(array([2, 5, 6, 7, 8, 9]), array([3, 2, 2, 1, 1, 1], dtype=int64))

## 08.元素级数组函数
可以将其看做简单函数（接受一个或多个标量值，并产生一个或多个标量值）的矢量化包装器。  
**一元ufunc**  
![](https://upload-images.jianshu.io/upload_images/7178691-1d494e73b61c7ced.png?imageMogr2/auto-orient/)
![](https://upload-images.jianshu.io/upload_images/7178691-4e38d02a66481530.png?imageMogr2/auto-orient/)  
**二元ufunc**  
![](https://upload-images.jianshu.io/upload_images/7178691-eff1e61e5464159f.png?imageMogr2/auto-orient/)
![](https://upload-images.jianshu.io/upload_images/7178691-236dba83b6a420cc.png?imageMogr2/auto-orient/)  


## 09.Numpy字符串函数
以下函数用于对dtype为numpy.string_或numpy.unicode_的数组执行向量化字符串操作。 它们基于 Python 内置库中的标准字符串函数。调用格式：np.char.add([],[])等。  
1.	add() 返回两个str或Unicode数组的逐个字符串连接
2.	multiply() 返回按元素多重连接后的字符串
3.	center() 返回给定字符串的副本，其中元素位于特定字符串的中央
4.	capitalize() 返回给定字符串的副本，其中只有第一个字符串大写
5.	title() 返回字符串或 Unicode 的按元素标题转换版本
6.	lower() 返回一个数组，其元素转换为小写
7.	upper() 返回一个数组，其元素转换为大写
8.	split() 返回字符串中的单词列表，并使用分隔符来分割
9.	splitlines() 返回元素中的行列表，以换行符分割
10.	strip() 返回数组副本，其中元素移除了开头或者结尾处的特定字符
11.	join() 返回一个字符串，它是序列中字符串的连接
12.	replace() 返回字符串的副本，其中所有子字符串的出现位置都被新字符串取代
13.	decode() 按元素调用str.decode
14.	encode() 按元素调用str.encode

Tips：舍入函数numpy.around(a,decimals)，decimals 要舍入的小数位数。 默认值为0。 如果为负，整数将四舍五入到小数点左侧的位置

## 10.Numpy统计函数
- np.amin()和numpy.amax()从给定数组中的元素沿指定轴返回最小值和最大值。  
- np.tp()函数返回沿轴的值的范围(最大值 - 最小值)。  
- np.percentile()百分位数是统计中使用的度量，表示小于这个值得观察值占某个百分比。 函数numpy.percentile()接受以下参数。numpy.percentile(a, q, axis),q 要计算的百分位数，在 0 ~ 100 之间。  
- np.median()中值定义为将数据样本的上半部分与下半部分分开的值。  
- np.mean()算术平均值是沿轴的元素的总和除以元素的数量。 numpy.mean()函数返回数组中元素的算术平均值。 如果提供了轴，则沿其计算。  
- np.average()加权平均值是由每个分量乘以反映其重要性的因子得到的平均值。 numpy.average()函数根据在另一个数组中给出的各自的权重计算数组中元素的加权平均值。 该函数可以接受一个轴参数。 如果没有指定轴，则数组会被展开。  
- 标准差是与均值的偏差的平方的平均值的平方根。 标准差公式如下：
std = sqrt(mean((x - x.mean())**2))
如果数组是[1，2，3，4]，则其平均值为2.5。 因此，差的平方是[2.25,0.25,0.25,2.25]，并且其平均值的平方根除以4，即sqrt(5/4)是1.1180339887498949。

![](https://upload-images.jianshu.io/upload_images/7178691-a6c6df3ca8e0b98e.png?imageMogr2/auto-orient/)
![](https://upload-images.jianshu.io/upload_images/7178691-866fcde885b1d357.png?imageMogr2/auto-orient/)

## 11.排序、搜索和计数
&emsp;&emsp;NumPy中提供了各种排序相关功能。 这些排序函数实现不同的排序算法，每个排序算法的特征在于执行速度，最坏情况性能，所需的工作空间和算法的稳定性。 下表显示了三种排序算法的比较。    
- 'quicksort'(快速排序)	 O(n^2)        不稳定
- 'mergesort'(归并排序)	 O(n*log(n))   稳定
- 'heapsort'(堆排序)	  O(n*log(n))	不稳定

sort()函数返回输入数组的排序副本。 它有以下参数：
numpy.sort(a, axis, kind, order)
2.	axis 沿着它排序数组的轴，如果没有数组会被展开，沿着最后的轴排序
3.	kind 默认为'quicksort'(快速排序)
4.	order 如果数组包含字段，则是要排序的字段

In [82]:
import numpy as np  
a = np.array([[3,7],[9,1]])
a

array([[3, 7],
       [9, 1]])

In [83]:
np.sort(a)

array([[3, 7],
       [1, 9]])

In [84]:
np.sort(a, axis =  0)

array([[3, 1],
       [9, 7]])

numpy.argsort()函数对输入数组沿给定轴执行间接排序，并使用指定排序类型返回数据的索引数组。 这个索引数组用于构造排序后的数组。

In [86]:
import numpy as np 
x = np.array([3,  1,  2])  
x

array([3, 1, 2])

In [87]:
np.argsort(x) #返回排序后的索引

array([1, 2, 0], dtype=int64)

numpy.lexsort()函数使用键序列执行间接排序。 键可以看作是电子表格中的一列。 该函数返回一个索引数组，使用它可以获得排序数据。 注意，最后一个键恰好是 sort 的主键。

In [89]:
import numpy as np 
nm =  ('raju','anil','ravi','amar') 
dv =  ('f.y.',  's.y.',  's.y.',  'f.y.') 
ind = np.lexsort((dv,nm))
ind

array([3, 1, 0, 2], dtype=int64)

In [90]:
print([nm[i]  +  ", "  + dv[i]  for i in ind])

['amar, f.y.', 'anil, s.y.', 'raju, f.y.', 'ravi, s.y.']


numpy.argmax() 和 numpy.argmin()
这两个函数分别沿给定轴返回最大和最小元素的索引。  
numpy.nonzero()函数返回输入数组中非零元素的索引。  
where()函数返回输入数组中满足给定条件的元素的索引,是三元表达式x if condition else y的矢量化版本。

In [92]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [94]:
result = np.where(cond, xarr, yarr) #cond为true选择xarr，否则选yarr
result

array([ 1.1,  2.2,  1.3,  1.4,  2.5])

extract()函数返回满足任何条件的元素。

In [96]:
import numpy as np 
x = np.arange(9.).reshape(3,  3)  
x

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.]])

In [97]:
condition = np.mod(x,2) == 0 #条件:能整除2
np.extract(condition, x)

array([ 0.,  2.,  4.,  6.,  8.])

numpy.nonzero()函数返回输入数组中非零元素的索引。

In [5]:
import numpy as np 
a = np.array([[30,40,0],[0,20,10],[50,0,60]])  
a

array([[30, 40,  0],
       [ 0, 20, 10],
       [50,  0, 60]])

In [6]:
np.nonzero(a)

(array([0, 0, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 1, 2, 0, 2], dtype=int64))

## 12.线性代数
NumPy 包包含numpy.linalg模块，提供线性代数所需的所有功能。 此模块中的一些重要功能如下表所述。
1.	dot 两个数组的点积
2.	vdot 两个向量的点积
3.	inner 两个数组的内积
4.	matmul 两个数组的矩阵积
5.	determinant 数组的行列式
6.	solve 求解线性矩阵方程
7.	inv 寻找矩阵的乘法逆矩阵  

![](https://upload-images.jianshu.io/upload_images/7178691-dcdb66e49e5f70ea.png?imageMogr2/auto-orient/)  
**附录：Numpy产生随机数的函数**
![](https://upload-images.jianshu.io/upload_images/7178691-97ba09c96dab93a2.png?imageMogr2/auto-orient/)
![](https://upload-images.jianshu.io/upload_images/7178691-6ed04fae3d1178e2.png?imageMogr2/auto-orient/)

## 13.Numpy IO
ndarray对象可以保存到磁盘文件并从磁盘文件加载。 可用的 IO 功能有：

- load()和save()函数处理 numPy 二进制文件(带npy扩展名)

- loadtxt()和savetxt()函数处理正常的文本文件

NumPy 为ndarray对象引入了一个简单的文件格式。 这个npy文件在磁盘文件中，存储重建ndarray所需的数据、图形、dtype和其他信息，以便正确获取数组，即使该文件在具有不同架构的另一台机器上。